const $ = (id) => document.getElementById(id);
let audioRecorder, videoRecorder, audioChunks = [], videoChunks = [], cameraStream, videoStream;
let currentAudioId = null;
let currentStimulus = null;
let lastRuntimeState = '';
let activeSessionId = null;
let navigationSignature = '';
const items = ["spoon","book","kangaroo","penguin","anchor","camel","harp","rhinoceros","barrel","crown","crocodile","accordion"];

function debug(message,detail){const output=$('debug-console');const suffix=detail===undefined?'':` ${typeof detail==='string'?detail:JSON.stringify(detail)}`;output.textContent+=`[${new Date().toLocaleTimeString()}] ${message}${suffix}\n`;const lines=output.textContent.split('\n');if(lines.length>201)output.textContent=lines.slice(-201).join('\n');output.scrollTop=output.scrollHeight}
$('clear-console').onclick=()=>{$('debug-console').textContent='';debug('Console cleared')};
async function api(path, options={}) { const r=await fetch(path,options); if(!r.ok){let detail=r.statusText;try{detail=(await r.json()).detail||detail}catch(e){}throw new Error(`${r.status} ${detail}`)} return r.json(); }
async function loadDefaults(){try{const config=await api('api/config');for(const [name,value] of Object.entries(config.leader_defaults||{})){const input=document.querySelector(`[name="${name}"]`);if(input&&!input.value)input.value=value}}catch(e){}}
debug('ACE page loaded');loadDefaults().then(()=>debug('System defaults loaded'));
$('start-form').onsubmit = async (event) => { event.preventDefault(); const f=new FormData(event.target); try {
  await api('api/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({
    patient:{name:f.get('patient_name'),dob:f.get('dob')}, assessor:f.get('assessor'),
    location:{number:f.get('number'),street:f.get('street'),town:f.get('town'),county:f.get('county'),country:f.get('country')},
    current_uk_pm:f.get('uk_pm'),current_us_president:f.get('us_president'),previous_uk_pm:f.get('previous_uk_pm')||null,
    previous_us_president:f.get('previous_us_president')||null,synthesize_audio:!!f.get('synthesize')})});
  currentAudioId=null;$('audio').removeAttribute('src');$('setup').classList.add('hidden'); $('assessment-layout').classList.remove('hidden');debug('Session started');
} catch(e){debug('Session start failed',e.message);alert(e.message)} };
$('resume-form').onsubmit=async event=>{event.preventDefault();try{await api(`api/sessions/${$('resume-id').value.trim()}/resume`,{method:'POST'});currentAudioId=null;$('audio').removeAttribute('src');$('setup').classList.add('hidden');$('assessment-layout').classList.remove('hidden')}catch(e){alert(e.message)}};

function show(id, yes){$(id).classList.toggle('hidden',!yes)}
function renderNavigation(navigation,currentDomain){const domains=navigation?.domains||[];const signature=JSON.stringify([navigation?.can_jump,currentDomain,domains]);if(signature===navigationSignature)return;navigationSignature=signature;const list=$('domain-list');list.replaceChildren();for(const domain of domains){const item=document.createElement('li');const button=document.createElement('button');const name=document.createElement('span');const count=document.createElement('small');button.type='button';button.className=`domain-link ${domain.status}`;button.disabled=!navigation.can_jump;button.setAttribute('aria-current',domain.name===currentDomain?'step':'false');name.textContent=domain.name;count.textContent=`${domain.completed}/${domain.total}`;button.append(name,count);if(navigation.can_jump)button.onclick=async()=>{if(domain.status==='complete'&&!confirm(`Restart ${domain.name}? Existing results for this module will be replaced.`))return;try{debug('Module jump requested',{domain:domain.name});await api('api/sessions/jump',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain:domain.name})})}catch(e){debug('Module jump failed',e.message);$('error').textContent=e.message}};item.append(button);list.append(item)}$('navigation-hint').textContent=navigation?.can_jump?'Debug navigation enabled. Select a module to jump to it.':'Progress is view only for this session.'}
const renderDomainDirectory=renderNavigation;renderNavigation=(navigation,currentDomain)=>{$('previous-question').disabled=!navigation?.can_jump;$('next-question').disabled=!navigation?.can_jump;return renderDomainDirectory(navigation,currentDomain)};
async function jumpQuestion(direction){try{debug('Question jump requested',{direction});const result=await api('api/sessions/jump-question',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({direction})});debug('Question jump accepted',result)}catch(e){debug('Question jump failed',e.message);$('error').textContent=e.message}}
$('previous-question').onclick=()=>jumpQuestion('previous');$('next-question').onclick=()=>jumpQuestion('next');
async function poll(){try{const audioQuery=currentAudioId?`?known_audio_id=${encodeURIComponent(currentAudioId)}`:'';const s=await api(`api/sessions/current${audioQuery}`);if(s.session_id!==activeSessionId){activeSessionId=s.session_id;$('setup').classList.add('hidden');$('assessment-layout').classList.remove('hidden');debug('Attached to session',{session_id:s.session_id})}$('status-text').textContent=s.status; $('prompt').textContent=s.prompt||'Processing…'; $('error').textContent=s.error||'';const progress=s.progress||{};const total=Number(progress.total)||0;const current=Number(progress.current)||0;const percent=total?Math.min(100,Math.round(current/total*100)):0;$('progress-label').textContent=total?`${current} of ${total} completed`:'Preparing…';$('progress-bar').style.width=`${percent}%`;$('progress-track').setAttribute('aria-valuenow',String(percent));renderNavigation(s.navigation,progress.domain);const runtimeState=`${s.status}:${s.awaiting||'-'}`;if(runtimeState!==lastRuntimeState){lastRuntimeState=runtimeState;debug('Runtime state',{status:s.status,awaiting:s.awaiting})}
  if(s.audio&&s.audio.id!==currentAudioId){currentAudioId=s.audio.id;debug('New TTS audio',{id:s.audio.id,mime_type:s.audio.mime_type,base64_chars:s.audio.data_base64.length});$('audio').src=`data:${s.audio.mime_type};base64,${s.audio.data_base64}`}
  show('stimulus',!!s.stimulus);if(s.stimulus!==currentStimulus){currentStimulus=s.stimulus;if(s.stimulus){$('stimulus').src=s.stimulus;debug('Stimulus changed',{src:s.stimulus})}else{$('stimulus').removeAttribute('src')}}
  show('audio-controls',s.awaiting==='audio'); show('image-controls',s.awaiting==='image'); show('video-controls',s.awaiting==='video'); show('click-controls',s.awaiting==='click');
  if(s.awaiting==='image'&&!cameraStream){cameraStream=await navigator.mediaDevices.getUserMedia({video:true});$('camera').srcObject=cameraStream;debug('Camera preview started')}
  else if(cameraStream&&$('camera').srcObject!==cameraStream){$('camera').srcObject=cameraStream}
  if(s.awaiting==='video'&&!videoStream){videoStream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});$('video-preview').srcObject=videoStream;debug('Video preview started')}
  else if(videoStream&&$('video-preview').srcObject!==videoStream){$('video-preview').srcObject=videoStream}
}catch(e){if(!e.message.startsWith('404 '))debug('Status poll failed',e.message)} setTimeout(poll,900)} poll();

$('audio').onplay=()=>debug('TTS playback started');$('audio').onended=()=>debug('TTS playback ended');$('audio').onerror=()=>debug('TTS playback error',$('audio').error?.message||'unknown media error');
$('record').onclick=async()=>{try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioChunks=[];const preferred='audio/webm;codecs=opus';const options=MediaRecorder.isTypeSupported(preferred)?{mimeType:preferred}:undefined;audioRecorder=new MediaRecorder(stream,options);audioRecorder.ondataavailable=e=>{if(e.data.size)audioChunks.push(e.data)};audioRecorder.start();debug('Recording started',{mime_type:audioRecorder.mimeType});$('record').disabled=true;$('stop').disabled=false}catch(e){debug('Microphone start failed',e.message)}};
$('stop').onclick=()=>{debug('Recording stop requested');$('stop').disabled=true;audioRecorder.onstop=async()=>{const blob=new Blob(audioChunks,{type:audioRecorder.mimeType});debug('Recording captured',{mime_type:blob.type,size_bytes:blob.size,chunks:audioChunks.length});const f=new FormData();f.append('audio',blob,'answer.webm');try{debug('Uploading audio');const result=await api('api/answers/audio',{method:'POST',body:f});debug('ASR accepted',{transcript:result.transcript})}catch(e){debug('Audio upload/ASR failed',e.message);$('error').textContent=e.message}finally{audioRecorder.stream.getTracks().forEach(t=>t.stop());$('record').disabled=false}};audioRecorder.stop()};
$('capture').onclick=async()=>{const v=$('camera'),c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);c.toBlob(async blob=>{const f=new FormData();f.append('kind','image');f.append('media',blob,'capture.png');await api('api/answers/media',{method:'POST',body:f})},'image/png')};
$('record-video').onclick=()=>{videoChunks=[];videoRecorder=new MediaRecorder(videoStream);videoRecorder.ondataavailable=e=>videoChunks.push(e.data);videoRecorder.start();$('record-video').disabled=true;$('stop-video').disabled=false};
$('stop-video').onclick=()=>{videoRecorder.onstop=async()=>{const f=new FormData();f.append('kind','video');f.append('media',new Blob(videoChunks,{type:videoRecorder.mimeType}),'action.webm');await api('api/answers/media',{method:'POST',body:f})};videoRecorder.stop();$('record-video').disabled=false;$('stop-video').disabled=true};
items.forEach(name=>{const b=document.createElement('button');b.textContent=name;b.onclick=()=>api('api/answers/click',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:name})});$('click-controls').appendChild(b)});
$('text-form').onsubmit=async e=>{e.preventDefault();await api('api/answers/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:$('text-answer').value})});$('text-answer').value=''};
$('pause').onclick=async()=>{try{const r=await api('api/sessions/pause',{method:'POST'});alert(`Saved ${r.checkpoint}`)}catch(e){alert(e.message)}};
